// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: bidder.proto

package bid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_bidder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_bidder_proto_rawDescGZIP(), []int{0}
}

type TpsBudget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxTps      float32 `protobuf:"fixed32,1,opt,name=max_tps,json=maxTps,proto3" json:"max_tps,omitempty"`
	MinTps      float32 `protobuf:"fixed32,2,opt,name=min_tps,json=minTps,proto3" json:"min_tps,omitempty"`
	MaxSpend    float32 `protobuf:"fixed32,3,opt,name=max_spend,json=maxSpend,proto3" json:"max_spend,omitempty"`            // pc_mint / second
	MaxBidDelta float32 `protobuf:"fixed32,4,opt,name=max_bid_delta,json=maxBidDelta,proto3" json:"max_bid_delta,omitempty"` // changes in bid deposit per slot as a %
}

func (x *TpsBudget) Reset() {
	*x = TpsBudget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TpsBudget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TpsBudget) ProtoMessage() {}

func (x *TpsBudget) ProtoReflect() protoreflect.Message {
	mi := &file_bidder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TpsBudget.ProtoReflect.Descriptor instead.
func (*TpsBudget) Descriptor() ([]byte, []int) {
	return file_bidder_proto_rawDescGZIP(), []int{1}
}

func (x *TpsBudget) GetMaxTps() float32 {
	if x != nil {
		return x.MaxTps
	}
	return 0
}

func (x *TpsBudget) GetMinTps() float32 {
	if x != nil {
		return x.MinTps
	}
	return 0
}

func (x *TpsBudget) GetMaxSpend() float32 {
	if x != nil {
		return x.MaxSpend
	}
	return 0
}

func (x *TpsBudget) GetMaxBidDelta() float32 {
	if x != nil {
		return x.MaxBidDelta
	}
	return 0
}

type Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*Stats_Network
	//	*Stats_Pipeline
	//	*Stats_Deposit
	Data isStats_Data `protobuf_oneof:"data"`
}

func (x *Stats) Reset() {
	*x = Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_bidder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_bidder_proto_rawDescGZIP(), []int{2}
}

func (m *Stats) GetData() isStats_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Stats) GetNetwork() *NetworkStats {
	if x, ok := x.GetData().(*Stats_Network); ok {
		return x.Network
	}
	return nil
}

func (x *Stats) GetPipeline() *PipelineStats {
	if x, ok := x.GetData().(*Stats_Pipeline); ok {
		return x.Pipeline
	}
	return nil
}

func (x *Stats) GetDeposit() *PipelineDeposit {
	if x, ok := x.GetData().(*Stats_Deposit); ok {
		return x.Deposit
	}
	return nil
}

type isStats_Data interface {
	isStats_Data()
}

type Stats_Network struct {
	Network *NetworkStats `protobuf:"bytes,1,opt,name=network,proto3,oneof"`
}

type Stats_Pipeline struct {
	Pipeline *PipelineStats `protobuf:"bytes,2,opt,name=pipeline,proto3,oneof"`
}

type Stats_Deposit struct {
	Deposit *PipelineDeposit `protobuf:"bytes,3,opt,name=deposit,proto3,oneof"`
}

func (*Stats_Network) isStats_Data() {}

func (*Stats_Pipeline) isStats_Data() {}

func (*Stats_Deposit) isStats_Data() {}

type NetworkStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkTps float32 `protobuf:"fixed32,1,opt,name=network_tps,json=networkTps,proto3" json:"network_tps,omitempty"`
}

func (x *NetworkStats) Reset() {
	*x = NetworkStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStats) ProtoMessage() {}

func (x *NetworkStats) ProtoReflect() protoreflect.Message {
	mi := &file_bidder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStats.ProtoReflect.Descriptor instead.
func (*NetworkStats) Descriptor() ([]byte, []int) {
	return file_bidder_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkStats) GetNetworkTps() float32 {
	if x != nil {
		return x.NetworkTps
	}
	return 0
}

type PipelineStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PipelineId     string  `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	StakeRatio     float32 `protobuf:"fixed32,2,opt,name=stake_ratio,json=stakeRatio,proto3" json:"stake_ratio,omitempty"`
	Price          float32 `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Discount       float32 `protobuf:"fixed32,4,opt,name=discount,proto3" json:"discount,omitempty"`
	CurrentDeposit uint64  `protobuf:"varint,5,opt,name=current_deposit,json=currentDeposit,proto3" json:"current_deposit,omitempty"`
}

func (x *PipelineStats) Reset() {
	*x = PipelineStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidder_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineStats) ProtoMessage() {}

func (x *PipelineStats) ProtoReflect() protoreflect.Message {
	mi := &file_bidder_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineStats.ProtoReflect.Descriptor instead.
func (*PipelineStats) Descriptor() ([]byte, []int) {
	return file_bidder_proto_rawDescGZIP(), []int{4}
}

func (x *PipelineStats) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *PipelineStats) GetStakeRatio() float32 {
	if x != nil {
		return x.StakeRatio
	}
	return 0
}

func (x *PipelineStats) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PipelineStats) GetDiscount() float32 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *PipelineStats) GetCurrentDeposit() uint64 {
	if x != nil {
		return x.CurrentDeposit
	}
	return 0
}

type AdjustRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PipelineId   string `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	NewDeposit   uint64 `protobuf:"varint,2,opt,name=new_deposit,json=newDeposit,proto3" json:"new_deposit,omitempty"`
	DeadlineSlot uint64 `protobuf:"varint,3,opt,name=deadline_slot,json=deadlineSlot,proto3" json:"deadline_slot,omitempty"`
}

func (x *AdjustRequest) Reset() {
	*x = AdjustRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidder_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdjustRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustRequest) ProtoMessage() {}

func (x *AdjustRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bidder_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustRequest.ProtoReflect.Descriptor instead.
func (*AdjustRequest) Descriptor() ([]byte, []int) {
	return file_bidder_proto_rawDescGZIP(), []int{5}
}

func (x *AdjustRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *AdjustRequest) GetNewDeposit() uint64 {
	if x != nil {
		return x.NewDeposit
	}
	return 0
}

func (x *AdjustRequest) GetDeadlineSlot() uint64 {
	if x != nil {
		return x.DeadlineSlot
	}
	return 0
}

type Balance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pipeline *PipelineDeposit `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	PcVault  uint64           `protobuf:"varint,2,opt,name=pc_vault,json=pcVault,proto3" json:"pc_vault,omitempty"`
	Sol      uint64           `protobuf:"varint,3,opt,name=sol,proto3" json:"sol,omitempty"`
}

func (x *Balance) Reset() {
	*x = Balance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidder_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_bidder_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_bidder_proto_rawDescGZIP(), []int{6}
}

func (x *Balance) GetPipeline() *PipelineDeposit {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *Balance) GetPcVault() uint64 {
	if x != nil {
		return x.PcVault
	}
	return 0
}

func (x *Balance) GetSol() uint64 {
	if x != nil {
		return x.Sol
	}
	return 0
}

type PipelineDeposit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PipelineId string  `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Deposit    uint64  `protobuf:"varint,2,opt,name=deposit,proto3" json:"deposit,omitempty"`
	Share      float32 `protobuf:"fixed32,3,opt,name=share,proto3" json:"share,omitempty"` // out of 1.0
	DecayRate  float32 `protobuf:"fixed32,4,opt,name=decay_rate,json=decayRate,proto3" json:"decay_rate,omitempty"`
}

func (x *PipelineDeposit) Reset() {
	*x = PipelineDeposit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidder_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipelineDeposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineDeposit) ProtoMessage() {}

func (x *PipelineDeposit) ProtoReflect() protoreflect.Message {
	mi := &file_bidder_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineDeposit.ProtoReflect.Descriptor instead.
func (*PipelineDeposit) Descriptor() ([]byte, []int) {
	return file_bidder_proto_rawDescGZIP(), []int{7}
}

func (x *PipelineDeposit) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *PipelineDeposit) GetDeposit() uint64 {
	if x != nil {
		return x.Deposit
	}
	return 0
}

func (x *PipelineDeposit) GetShare() float32 {
	if x != nil {
		return x.Share
	}
	return 0
}

func (x *PipelineDeposit) GetDecayRate() float32 {
	if x != nil {
		return x.DecayRate
	}
	return 0
}

type TimePoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payout *Payout `protobuf:"bytes,1,opt,name=payout,proto3" json:"payout,omitempty"`
}

func (x *TimePoint) Reset() {
	*x = TimePoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidder_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimePoint) ProtoMessage() {}

func (x *TimePoint) ProtoReflect() protoreflect.Message {
	mi := &file_bidder_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimePoint.ProtoReflect.Descriptor instead.
func (*TimePoint) Descriptor() ([]byte, []int) {
	return file_bidder_proto_rawDescGZIP(), []int{8}
}

func (x *TimePoint) GetPayout() *Payout {
	if x != nil {
		return x.Payout
	}
	return nil
}

type Payout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Payout) Reset() {
	*x = Payout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bidder_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payout) ProtoMessage() {}

func (x *Payout) ProtoReflect() protoreflect.Message {
	mi := &file_bidder_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payout.ProtoReflect.Descriptor instead.
func (*Payout) Descriptor() ([]byte, []int) {
	return file_bidder_proto_rawDescGZIP(), []int{9}
}

var File_bidder_proto protoreflect.FileDescriptor

var file_bidder_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x69, 0x64, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x62, 0x69, 0x64, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x7e, 0x0a, 0x09,
	0x54, 0x70, 0x73, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78,
	0x5f, 0x74, 0x70, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x54,
	0x70, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x5f, 0x74, 0x70, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x54, 0x70, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6d,
	0x61, 0x78, 0x5f, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08,
	0x6d, 0x61, 0x78, 0x53, 0x70, 0x65, 0x6e, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x5f,
	0x62, 0x69, 0x64, 0x5f, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x0b, 0x6d, 0x61, 0x78, 0x42, 0x69, 0x64, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x22, 0xa2, 0x01, 0x0a,
	0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x69, 0x64, 0x2e, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x73, 0x48, 0x00, 0x52, 0x07, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x30, 0x0a, 0x08, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x69, 0x64, 0x2e, 0x50, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x48, 0x00, 0x52, 0x08, 0x70,
	0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x64, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x69, 0x64, 0x2e, 0x50,
	0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x48, 0x00,
	0x52, 0x07, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x2f, 0x0a, 0x0c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x74, 0x70, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x54,
	0x70, 0x73, 0x22, 0xac, 0x01, 0x0a, 0x0d, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x69, 0x70, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x5f, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x6b,
	0x65, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08,
	0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x22, 0x76, 0x0a, 0x0d, 0x41, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x65, 0x77, 0x5f, 0x64, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65,
	0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x64, 0x65, 0x61,
	0x64, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x22, 0x68, 0x0a, 0x07, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x69, 0x64, 0x2e, 0x50, 0x69, 0x70,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x08, 0x70, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x63, 0x5f, 0x76, 0x61, 0x75,
	0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x70, 0x63, 0x56, 0x61, 0x75, 0x6c,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x73, 0x6f, 0x6c, 0x22, 0x81, 0x01, 0x0a, 0x0f, 0x50, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x69, 0x70, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x69,
	0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x64, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x63, 0x61,
	0x79, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x64, 0x65,
	0x63, 0x61, 0x79, 0x52, 0x61, 0x74, 0x65, 0x22, 0x30, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x06, 0x70, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x69, 0x64, 0x2e, 0x50, 0x61, 0x79, 0x6f, 0x75,
	0x74, 0x52, 0x06, 0x70, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x22, 0x08, 0x0a, 0x06, 0x50, 0x61, 0x79,
	0x6f, 0x75, 0x74, 0x32, 0xbd, 0x01, 0x0a, 0x05, 0x42, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x2e, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x54, 0x70, 0x73, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x12, 0x0a, 0x2e,
	0x62, 0x69, 0x64, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0e, 0x2e, 0x62, 0x69, 0x64, 0x2e,
	0x54, 0x70, 0x73, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x22, 0x00, 0x30, 0x01, 0x12, 0x30, 0x0a,
	0x0c, 0x53, 0x65, 0x74, 0x54, 0x70, 0x73, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x12, 0x0e, 0x2e,
	0x62, 0x69, 0x64, 0x2e, 0x54, 0x70, 0x73, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x1a, 0x0e, 0x2e,
	0x62, 0x69, 0x64, 0x2e, 0x54, 0x70, 0x73, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x22, 0x00, 0x12,
	0x26, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x0a, 0x2e, 0x62, 0x69,
	0x64, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0a, 0x2e, 0x62, 0x69, 0x64, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x22, 0x00, 0x30, 0x01, 0x12, 0x2a, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x0a, 0x2e, 0x62, 0x69, 0x64, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x0c, 0x2e, 0x62, 0x69, 0x64, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x53, 0x6f, 0x6c, 0x6d, 0x61, 0x74, 0x65, 0x44, 0x65, 0x76, 0x2f, 0x67, 0x6f, 0x2d,
	0x73, 0x74, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x69, 0x64,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bidder_proto_rawDescOnce sync.Once
	file_bidder_proto_rawDescData = file_bidder_proto_rawDesc
)

func file_bidder_proto_rawDescGZIP() []byte {
	file_bidder_proto_rawDescOnce.Do(func() {
		file_bidder_proto_rawDescData = protoimpl.X.CompressGZIP(file_bidder_proto_rawDescData)
	})
	return file_bidder_proto_rawDescData
}

var file_bidder_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_bidder_proto_goTypes = []interface{}{
	(*Empty)(nil),           // 0: bid.Empty
	(*TpsBudget)(nil),       // 1: bid.TpsBudget
	(*Stats)(nil),           // 2: bid.Stats
	(*NetworkStats)(nil),    // 3: bid.NetworkStats
	(*PipelineStats)(nil),   // 4: bid.PipelineStats
	(*AdjustRequest)(nil),   // 5: bid.AdjustRequest
	(*Balance)(nil),         // 6: bid.Balance
	(*PipelineDeposit)(nil), // 7: bid.PipelineDeposit
	(*TimePoint)(nil),       // 8: bid.TimePoint
	(*Payout)(nil),          // 9: bid.Payout
}
var file_bidder_proto_depIdxs = []int32{
	3, // 0: bid.Stats.network:type_name -> bid.NetworkStats
	4, // 1: bid.Stats.pipeline:type_name -> bid.PipelineStats
	7, // 2: bid.Stats.deposit:type_name -> bid.PipelineDeposit
	7, // 3: bid.Balance.pipeline:type_name -> bid.PipelineDeposit
	9, // 4: bid.TimePoint.payout:type_name -> bid.Payout
	0, // 5: bid.Brain.GetTpsBudget:input_type -> bid.Empty
	1, // 6: bid.Brain.SetTpsBudget:input_type -> bid.TpsBudget
	0, // 7: bid.Brain.GetStats:input_type -> bid.Empty
	0, // 8: bid.Brain.GetBalance:input_type -> bid.Empty
	1, // 9: bid.Brain.GetTpsBudget:output_type -> bid.TpsBudget
	1, // 10: bid.Brain.SetTpsBudget:output_type -> bid.TpsBudget
	2, // 11: bid.Brain.GetStats:output_type -> bid.Stats
	6, // 12: bid.Brain.GetBalance:output_type -> bid.Balance
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_bidder_proto_init() }
func file_bidder_proto_init() {
	if File_bidder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bidder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bidder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TpsBudget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bidder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bidder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bidder_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bidder_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdjustRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bidder_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Balance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bidder_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipelineDeposit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bidder_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimePoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bidder_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bidder_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Stats_Network)(nil),
		(*Stats_Pipeline)(nil),
		(*Stats_Deposit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bidder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bidder_proto_goTypes,
		DependencyIndexes: file_bidder_proto_depIdxs,
		MessageInfos:      file_bidder_proto_msgTypes,
	}.Build()
	File_bidder_proto = out.File
	file_bidder_proto_rawDesc = nil
	file_bidder_proto_goTypes = nil
	file_bidder_proto_depIdxs = nil
}
